//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatTopicsDemo2023.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupChat
    {
        public int Id_GroupChat { get; set; }
        public int Sender_Id { get; set; }
        public int Chatroom_Id { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Chatroom Chatroom { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
